### PR TITLE
Adds a cop for validating against rails I18n

### PR DESCRIPTION
**Pull request by kbacha**
Many repos use rails for I18n so this commit adds a check to make sure
that sentence-like strings are wrapped in the translate function.

### CODE REVIEW

**Comment by kbacha** [comment]
@highb Would you mind taking a look at my proposed i18n cops for the i18n gem?

**Comment by kbacha** [comment]
@highb Awesome! Thanks for taking a look!

We are looking at even more ways to enforce best practices for i18n, so I hope it's ok for me to keep bringing updates as well!

**Comment by highb** [comment]
Yep, more updates welcome.

**Comment by highb** [comment]
@kbacha One problem I forsee with this is that typically someone is going to be using either gettext or ruby-i18n or some other framework, but not all at once. Did you consider making the cop configurable (beyond disabling the other framework cops in `.rubocop.yml`) so that someone could easily set which translation framework they want to use? I'm trying to think of how I'd pull that off or if rubocop even supports that.

**Comment by kbacha** [comment]
In our rubocop.yml we have the following:

```yaml
GetText:
  Enabled: false
```

This disables all the GetText cops but keeps the RailsI18n cops open. This is the advantage of keeping them under different departments.

**Comment by highb** [comment]
That seems straightforward enough, and doesn't require any additional logic in the cops themselves. I'll add a note about that to the README, with an example config that allows easy copy-pasting. That probably means I'll be doing a major release of the gem, since current users that only want gettext will have to do some extra config to get the same behavior (seems like an "API" change.)

Thank you for contributing!

**Pull request merged**
