### PR TITLE
Add new cop RailsI18n/DecorateStringFormattingUsingInterpolation.

### PR DESCRIPTION
**Pull request by unixmonkey**
This nearly mirrors the behavior of
GetText/DecorateStringFormattingUsingInterpolation, which also checks for similar interpolation in a string, but inside a `t()` call, instead of `_()`.

It looks like this when run against a Rails app with a standard I18n setup:
```
app/reports/my_report.rb:114:22: C: RailsI18n/DecorateStringFormattingUsingInterpolation: 't' function, message key string should not contain #{} formatting
        type: I18n.t("questions.types.#{question.question_type}.title"),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Which is super helpful to us to find these, so we can prevent new ones from being introduced, and migrate away from the ones that currently exist.

There's a lot of duplication, but I wasn't sure how you'd like to abstract that out or not.
Please let me know what you think, and how I can help make this shippable.

### CODE REVIEW

**Comment by highb** [comment]
@unixmonkey Hey, thanks for the contribution and my apologies for not seeing it sooner. It looks like there are a few linting errors that need fixing, once those are in I think this would be fine to merge. The duplication is okay for now, I'm sure if it becomes an issue we can refactor it.

**Comment by unixmonkey** [comment]
@highb Thanks for the bump.

I see now that you've fixed or ignored the RuboCop errors, so I've updated this branch, and made the appropriate RuboCop fixes in the new rails_i18n files, then ported over those changes to the existing gettext files. I did add an extra ignore line for one rule in the spec, as it was warning about something we are explicitly testing for.

Please let me know if there's anything else you'd like me to do or help out with.

Thanks!

**Comment by highb** [comment]
@tphoney This looks good to me, anything comments for you?

**Comment by tphoney** [comment]
This looks good to me, however there was a previous merge, so we have a conflict. 

apologies @unixmonkey .

Nearly there, and many thanks

**Comment by tphoney** [comment]
great work @unixmonkey  !!

**Comment by HashNotAdam** [comment]
I'm having a hard time finding information that explains why this is important so I can decide if I want to follow the rule.

I can see a comment was added to `decorate_string_formatting_using_interpolation.rb` stating:

> the '#{}' interpolation string as this makes it hard to translate the strings.

But in what situation would Rails have trouble matching the key to the YAML translations because of string interpolation?

**Comment by unixmonkey** [comment]
That comment is duplicated from https://github.com/puppetlabs/rubocop-i18n/blob/master/lib/rubocop/cop/i18n/gettext/decorate_string_formatting_using_interpolation.rb#L7

I can see how that might be misinterpreted though. It does not make anything harder in code, but in the social human process of keeping translations maintainable in a large project.

For example, I often use [i18n-tasks](https://github.com/glebm/i18n-tasks) to help manage complexity of translations in a large project. This tool uses a static code scanner to inspect your project for what translation keys are being used, and which ones aren't, and warn you if someone removes a view, but leaves the translations used by that view behind (as dead code). It also helps find places where you might be calling `t()` on a key that doesn't exist.

However, as a static analysis tool, it has trouble with interpolations (but is surprisingly good with following variables, in many cases). Is it very easy to use interpolation to select the right key under a tree in code, but doing so inhibits static analysis, so we try to discourage that with a linter rule to enforce that preference.

So instead of:
```ruby
I18n.t("items.type.#{item.item_type}.description")
``

Which the scanner is unable to tell what keys are actually being used (because it does not understand what `item.item_type` might be).

We would prefer:
```ruby
case item.item_type
when "small" then I18n.t("items.type.small.description")
when "medium" then I18n.t("items.type.medium.description")
when "large" then I18n.t("items.type.large.description")
end
```

Which it can easily look up every used value and compare against the yml file values.

I hope that makes sense!

**Comment by HashNotAdam** [comment]
Really appreciate the explanation, thank you. This seems like a logical decision. I'll need to consider how to lint ERB files, but that's a problem for another place 😅

**Comment by unixmonkey** [comment]
I believe the same linter should also already work with ERB files also.

**Comment by HashNotAdam** [comment]
While technically true, Rubocop doesn't know how to parse ERB out of the box. I'm experimenting with [rubocop-erb](https://github.com/r7kamura/rubocop-erb) which seems to have solved the problem

**Pull request merged**
