### PR TITLE
Upgrade to RuboCop 1.0

### LINKED ISSUE #45: Changes will be needed after rubocop gem hits 1.0 version
In `rubocop` gem version 1.0 there will be a breaking change (https://github.com/rubocop-hq/rubocop/pull/8490) that will affect `rubocop-i18n`. That PR with a breaking change has been already merged into master so that means version 1.0 is going to be released reasonably soon. 

This is the description of the breaking change:

**Change logic for cop department name computation. Cops inside deep namespaces (5 or more levels deep) now belong to departments with names that are calculated by joining module names starting from the third one with slashes as separators. For example, cop `Rubocop::Cop::Foo::Bar::Baz` now belongs to `Foo/Bar` department (previously it was `Bar`).**

Due to this `rubocop-i18n` will need to update its documentation in `README.md` file to correctly address new department names. Basically the only thing to do is to add `I18n/` before all the departments and cop names that would go in `.rubocop.yml` file. This is required because all the cops in this gem are "deep" (5 levels of nesting).

So instead of this:
```
GetText:
RailsI18n:
GetText/DecorateString:
GetText/DecorateFunctionMessage:
GetText/DecorateStringFormattingUsingInterpolation:
GetText/DecorateStringFormattingUsingPercent:
RailsI18n/DecorateString:
RailsI18n/DecorateStringFormattingUsingInterpolation:
```
it should be like this:
```
I18n/GetText:
I18n/RailsI18n:
I18n/GetText/DecorateString:
I18n/GetText/DecorateFunctionMessage:
I18n/GetText/DecorateStringFormattingUsingInterpolation:
I18n/GetText/DecorateStringFormattingUsingPercent:
I18n/RailsI18n/DecorateString:
I18n/RailsI18n/DecorateStringFormattingUsingInterpolation:
```

As far as I can see it's the only change due to that PR.

### PR DESCRIPTION
**Pull request by mvz**
Fixes #45

### CODE REVIEW

**Comment by coding-bunny** [comment]
Any update regarding this? As this is blocking upgrading to Rubocop 1.x

**Comment by wagenet** [comment]
@tphoney ?

**Comment by wagenet** [comment]
@highb ?

**Comment by highb** [comment]
@wagenet I'll take a look when I have a moment today. Thanks for pinging me! As an FYI, I'm no longer working at Puppet and when I left Puppet no longer had an i18n team so maintenance of this repo may become a challenge as time goes on. If you wanted to try to find a path to co-maintainership, I can try reaching out to my contacts at Puppet to figure that out.

That being said, I do still have permission to review PRs so I'll add my eyeballs. Thank you for your patience!

**Comment by wagenet** [comment]
@highb thanks for taking a look! Unfortunately, I'm unlikely to be able to contribute myself. My main concern in getting this moving again is because another dependency that I rely upon needs this one, even though I don't use the features. That said, this change does seem plausible to me.

**Review by highb — APPROVED** [review]
👍 It seems like this should be compatible with Rubocop 1.0. I think in addition to this change, there should probably be a major version bump in this gem so that users aren't caught by surprise.

**Comment by highb** [comment]
Approved, but unable to merge. Hopefully someone at Puppet can take a look soon. 🤞

**Comment by ThomasKoppensteiner** [comment]
@tphoney or @HelenCampbell it looks like you contributed to this repository in the past. Can you please review and merge this PR?

**Comment by highb** [comment]
Just re-verified locally that tests pass, and rubocop checks are happy so going to merge now.

**Comment by rickychilcott** [comment]
@highb thank you for your work on this and for cutting the 3.0 release. I see this repo is no longer archived. Are you going to continue to play a role in maintaining for at least a little while?

**Comment by highb** [comment]
@rickychilcott Yep, that's my plan. I'll continue to maintain this in my personal time. As noted, the repo is unarchived and I have admin access on the repo now so I should be able to perform any necessary maintainership tasks. I also have contacts within the Puppet team that I can reach out to if we encounter any issues.

**Pull request merged**
