### PR TITLE
(PUP-8038) remove support for DecorateString

### PR DESCRIPTION
**Pull request by ericldelaney**
We don't really want to force every string in a probject to be decorated.
It would be better to add more cops that look for specific function names that should contain
decorated strings

### CODE REVIEW

**Comment by ericldelaney** [comment]
@highb Do you have a chance to review this.


I tried to make DecorateString smarter, but the problem you rapidly
run into is there are a lot of strings that you don't want to have
to decorate or put in comments to ignore.

For example

The second string is deleted as needing decoration
   gem "rubocopy-i18n", "~> 0.1.2"

This is a string that doesn't need decoration
   gzip = %x{which gzip}

More strings that that we find:
   opts.on('--[no-]rdoc', 'Prevents the creation of RDoc output.', 'Default on.') do |onrdoc|
   :desc     => "The directory in which to store log files",

**Comment by highb** [comment]
@ericldelaney I'm not sure removing the linter entirely is the way to go. Perhaps we could just make it better at detection by looking for a sentence that contains not only spaces, but spaces and punctuation. Not every string that requires translation is necessarily being passed directly into a function -- sometimes they are built up over multiple lines. @tphoney @HelenCampbell What are your thoughts?

**Comment by highb** [comment]
@ericldelaney @tphoney @HelenCampbell What if we refined DecorateString to only look at grammatically correct sentences like this? https://github.com/puppetlabs/rubocop-i18n/pull/21

**Comment by ericldelaney** [comment]
@highb @tphoney @HelenCampbell 

I started out thinking the same thing, I even worked on making DecorateString smarter,

https://github.com/ericldelaney/rubocop-i18n/tree/task/master/PUP-8038/fix_decorate_string_cop

but its a large number of things it complains about when you get around to running it. So even with my update updated cop which skips strings with no spaces, strings that are hash keys, regexps, we still have an insane number of errors in the puppet code base:

1061 files inspected, 5448 offenses detected

Looking at the errors you find things like the this:

All your file version entries:
C: 18: 20: GetText/DecorateString: decorator is missing around string, instead found gem

The install script doing things. There are paths and program names in here:
== install.rb ==
C: 43:  8: GetText/DecorateString: decorator is missing around string, instead found puts
C: 80: 12: GetText/DecorateString: decorator is missing around string, instead found warn
C:114: 17: GetText/DecorateString: decorator is missing around string
      gzip = %x{which gzip}
      gzip.chomp!
      %x{#{gzip} -f #{omf}}

== lib/puppet/application/describe.rb ==
    patt = Regexp.new("\\A(.{0,#{textLen}})[ \n]")
    prefix = " " * indent
    prefix + res.join("\n#{prefix}")
    "\n#{txt}\n" + sep * txt.size


Then you have things like this:
    File.open(hiera_yaml, 'w') do |f|
      f.puts(<<-YAML)
version: 4
datadir: data
hierarchy:
  - name: Common
    backend: yaml
    path: common
  - name: Configured
    backend: yaml
    path: "%{confdir}/data"
      YAML
    end

So after running the updated cop I pulled out a lot of the head hitters (the number is the count off occurrence) and the name at the end if the method applied to the string:

   8  decorator is missing around string, instead found warn
   9  decorator is missing around string, instead found *
   9  decorator is missing around string, instead found newtest
   9  decorator is missing around string, instead found returns
   9  decorator is missing around string, instead found summary
   9  decorator is missing around string, instead found warn_once
  10  decorator is missing around string, instead found gsub!
  10  decorator is missing around string, instead found notes
  10  decorator is missing around string, instead found push_context
  11  decorator is missing around string, instead found deprecation_warning
  11  decorator is missing around string, instead found to_sym
  12  decorator is missing around string, instead found split
  16  decorator is missing around string, instead found freeze
  16  decorator is missing around string, instead found gem
  17  decorator is missing around string, instead found gsub
  17  decorator is missing around string, instead found notice
  17  decorator is missing around string, instead found raise_invalid_parameters_error
  18  decorator is missing around string, instead found devfail
  18  decorator is missing around string, instead found execute
  19  decorator is missing around string, instead found copyright
  19  decorator is missing around string, instead found log
  20  decorator is missing around string, instead found send
  21  decorator is missing around string, instead found warning
  24  decorator is missing around string, instead found param
  26  decorator is missing around string, instead found %
  32  decorator is missing around string, instead found examples
  36  decorator is missing around string, instead found type
  38  decorator is missing around string, instead found feature
  48  decorator is missing around string, instead found on
  48  decorator is missing around string, instead found option
  60  decorator is missing around string, instead found description
  64  decorator is missing around string, instead found assert_instance_of
  64  decorator is missing around string, instead found fail
 102  decorator is missing around string, instead found new
 105  decorator is missing around string, instead found puts
 126  decorator is missing around string, instead found +
 182  decorator is missing around string, instead found join
 212  decorator is missing around string, instead found <<
 261  decorator is missing around string, instead found debug
 533  decorator is missing around string, instead found raise
 554  decorator is missing around string, instead found desc
1306  decorator is missing around string

We're probably better off adding methods that check for specific method names like the DecorateFunctionMessage does.

**Comment by highb** [comment]
Improving the regex to use `/^[[:upper:]][[:alpha:]]*[[:blank:]]+.*[.!?]/`, as I did in https://github.com/puppetlabs/rubocop-i18n/pull/21 , removes nearly all the false positives, although it will also fire alongside the other cops if the string isn't decorated correctly.

**Comment by ericldelaney** [comment]
@highb 

So my version against puppet (for a baseline)
1061 files inspected, 5448 offenses detected

Now with your regexp to ONLY look at things that match it
1061 files inspected, 3981 offenses detected

Here are some of the examples of things it tags as needed 

if File.exists? "#{__FILE__}.local"
  eval(File.read("#{__FILE__}.local"), binding)
warn "Failed to create puppet eventlog registry key: #{e}"

opts.on('--full', 'Performs a full installation. All', 'optional installation steps are run.') do |full|      f.puts(<<-YAML)
---
:backends: yaml
:yaml:
   :datadir: #{datadir}
:hierarchy:
   - common
   - groups
:logger: noop
      YAML
  
fname = "handle_#{long}".intern
self.options["#{long}".to_sym] = value
puts "#{Puppet.version}"

Thinking about how many messages that would get translated actually include any type of punctuation?

**Comment by highb** [comment]
@ericldelaney I noticed that when running it on the puppet source, too. I updated it to just look for [.?!] instead of any punctuation and that seemed to help quite a bit

**Comment by Magisus** [comment]
You might also want to allow it to not complain about messages passed to the debug logging function. We currently don't want to translate debug messages in Puppet.

**Comment by highb** [comment]
@Magisus I like the idea of making it more configurable with an ignore list.

**Comment by ericldelaney** [comment]
I worked with Brandon and we're come up with a regexp that limits the pattern enough to make it worth doing. So I'm going to close this one PR and do a different PR for that.

**Pull request closed without merging**
